# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170507_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['state', 'estimate']},
        ),
        migrations.AlterField(
            model_name='scores',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 12, 12, 32, 34905, tzinfo=utc)),
        ),
    ]
