# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 22:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170507_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 8, 22, 28, 13, 563160, tzinfo=utc)),
        ),
    ]
