# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170508_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scores',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='scores',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 8, 23, 12, 27, 526423, tzinfo=utc)),
        ),
    ]
